"""Phase 3 : conversations avec Cô Mai, ligues, défis entre amis, défi express.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-15
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | Sequence[str] | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('division', sa.Integer(), nullable=False),
    sa.Column('group_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_league_groups')),
    sa.UniqueConstraint('week_start', 'division', 'group_index', name=op.f('uq_league_groups_week_start'))
    )
    with op.batch_alter_table('league_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_groups_week_start'), ['week_start'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('topic_lesson_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fluency', sa.Integer(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('express_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('game', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_express_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_express_scores'))
    )
    with op.batch_alter_table('express_scores', schema=None) as batch_op:
        batch_op.create_index('ix_express_scores_game_local_date', ['game', 'local_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_express_scores_user_id'), ['user_id'], unique=False)

    op.create_table('friend_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('invite_code', sa.String(length=8), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_friend_challenges_creator_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friend_challenges')),
    sa.UniqueConstraint('invite_code', name=op.f('uq_friend_challenges_invite_code'))
    )
    with op.batch_alter_table('friend_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friend_challenges_creator_id'), ['creator_id'], unique=False)

    op.create_table('league_members',
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('division', sa.Integer(), nullable=False),
    sa.Column('final_xp', sa.Integer(), nullable=True),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['league_groups.id'], name=op.f('fk_league_members_group_id_league_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_league_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('week_start', 'user_id', name=op.f('pk_league_members'))
    )
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_members_user_id'), ['user_id'], unique=False)

    op.create_table('conversation_turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('glosses_json', sa.JSON(), nullable=False),
    sa.Column('correction_json', sa.JSON(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_turns_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_turns')),
    sa.UniqueConstraint('conversation_id', 'position', name=op.f('uq_conversation_turns_conversation_id'))
    )
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_turns_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('friend_challenge_participants',
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['friend_challenges.id'], name=op.f('fk_friend_challenge_participants_challenge_id_friend_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_friend_challenge_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('challenge_id', 'user_id', name=op.f('pk_friend_challenge_participants'))
    )
    with op.batch_alter_table('friend_challenge_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friend_challenge_participants_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_challenge_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friend_challenge_participants_user_id'))

    op.drop_table('friend_challenge_participants')
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_turns_conversation_id'))

    op.drop_table('conversation_turns')
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_league_members_group_id'))

    op.drop_table('league_members')
    with op.batch_alter_table('friend_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friend_challenges_creator_id'))

    op.drop_table('friend_challenges')
    with op.batch_alter_table('express_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_express_scores_user_id'))
        batch_op.drop_index('ix_express_scores_game_local_date')

    op.drop_table('express_scores')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_created_at'))

    op.drop_table('conversations')
    with op.batch_alter_table('league_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_groups_week_start'))

    op.drop_table('league_groups')
    # ### end Alembic commands ###
