"""Phase 4 : rôles, studio de contenu (brouillons, publications, relectures), espace enseignant.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-15
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: str | Sequence[str] | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('pack_code', sa.String(length=64), nullable=False),
    sa.Column('join_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_classes_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes')),
    sa.UniqueConstraint('join_code', name=op.f('uq_classes_join_code'))
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('content_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pack_code', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_content_drafts_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_drafts')),
    sa.UniqueConstraint('pack_code', 'kind', 'doc_id', name=op.f('uq_content_drafts_pack_code'))
    )
    op.create_table('content_publications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pack_code', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('pack_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_content_publications_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_publications'))
    )
    with op.batch_alter_table('content_publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_publications_pack_code'), ['pack_code'], unique=False)

    op.create_table('content_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pack_code', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_content_reviews_reviewer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_reviews'))
    )
    with op.batch_alter_table('content_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_content_reviews_pack_kind_doc', ['pack_code', 'kind', 'doc_id'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('lesson_ids', sa.JSON(), nullable=False),
    sa.Column('unit_id', sa.String(length=128), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_assignments_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_class_id'), ['class_id'], unique=False)

    op.create_table('class_members',
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_members_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_class_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'user_id', name=op.f('pk_class_members'))
    )
    with op.batch_alter_table('class_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_members_user_id'), ['user_id'], unique=False)

    # Comptes existants : aucun rôle attribué (learner implicite). Batch : ALTER TABLE sous SQLite.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('roles')

    with op.batch_alter_table('class_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_members_user_id'))

    op.drop_table('class_members')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_class_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('content_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_content_reviews_pack_kind_doc')

    op.drop_table('content_reviews')
    with op.batch_alter_table('content_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_publications_pack_code'))

    op.drop_table('content_publications')
    op.drop_table('content_drafts')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_teacher_id'))

    op.drop_table('classes')
    # ### end Alembic commands ###
