"""Parcours complet : jetons e-mail, OAuth, grâce du refresh, gel daté, profil d'onboarding, BigInteger, index.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-15
"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: str | Sequence[str] | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Copie figée de app/services/badges.py (badges ajoutés par le contrat parcours §3).
_BADGE_NAMESPACE = uuid.UUID("5b0f6f7e-2c1a-4d4e-9a4b-7061726c6f00")
_BADGES = [
    ("streak_100", "assiduity", {"streakDays": 100}),
    ("streak_365", "assiduity", {"streakDays": 365}),
    ("words_500", "competence", {"conceptsLearned": 500}),
    ("no_north_accent", "competence", {"spotTheSouthItems": 30, "accuracy": 0.95}),
    ("culture_explorer", "culture", {"cultureCardsPassed": 20}),
    ("culture_unit", "culture", {"unitTestPassedWithTag": "culture"}),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_tokens_token_hash'))
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.alter_column('response_ms',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.create_index('ix_answers_user_id_created_at', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index('ix_certificates_user_id_level', ['user_id', 'level'], unique=False)

    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.alter_column('response_ms',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('xp_total',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('game_plays', schema=None) as batch_op:
        batch_op.alter_column('duration_ms',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.alter_column('final_xp',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leagues_enabled_explicit', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('entourage', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('self_level', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('last_reminded_on', sa.Date(), nullable=True))

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replaced_by_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('xp_gained',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('planned_seconds',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('duration_ms',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.create_index('ix_sessions_user_id_ended_at', ['user_id', 'ended_at'], unique=False)

    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frozen_from', sa.Date(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###

    badges = sa.table(
        'badges',
        sa.column('id', sa.String(36)),
        sa.column('code', sa.String(64)),
        sa.column('family', sa.String(16)),
        sa.column('criteria_json', sa.JSON()),
    )
    conn = op.get_bind()
    existing = set(conn.execute(sa.select(badges.c.code)).scalars())
    rows = [
        {'id': str(uuid.uuid5(_BADGE_NAMESPACE, code)), 'code': code, 'family': family, 'criteria_json': criteria}
        for code, family, criteria in _BADGES
        if code not in existing
    ]
    if rows:
        op.bulk_insert(badges, rows)


def downgrade() -> None:
    """Downgrade schema."""
    codes = [code for code, _, _ in _BADGES]
    badges = sa.table('badges', sa.column('id', sa.String(36)), sa.column('code', sa.String(64)))
    user_badges = sa.table('user_badges', sa.column('badge_id', sa.String(36)))
    ids = sa.select(badges.c.id).where(badges.c.code.in_(codes))
    op.execute(user_badges.delete().where(user_badges.c.badge_id.in_(ids)))
    op.execute(badges.delete().where(badges.c.code.in_(codes)))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified_at')

    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.drop_column('frozen_from')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_id_ended_at')
        batch_op.alter_column('duration_ms',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('planned_seconds',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('xp_gained',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_column('replaced_by_id')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('last_reminded_on')
        batch_op.drop_column('self_level')
        batch_op.drop_column('entourage')
        batch_op.drop_column('leagues_enabled_explicit')

    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.alter_column('final_xp',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('game_plays', schema=None) as batch_op:
        batch_op.alter_column('duration_ms',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('xp_total',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.alter_column('response_ms',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index('ix_certificates_user_id_level')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index('ix_answers_user_id_created_at')
        batch_op.alter_column('response_ms',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_user_id'))

    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
